name: distributor_flutter_android
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  git: ^2.2.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
