name: distributor_flutter_android
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  dfa_common:
    git:
      url: https://github.com/NikitaMasev/dfa_common.git
      ref: main
  crypto_wrapper:
    git:
      url: https://github.com/NikitaMasev/crypto_wrapper.git
      ref: main
dev_dependencies:
  lints: ^2.0.0
